include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: false # Made less strict
    strict-raw-types: false # Made less strict
    strict-inference: false # Made less strict
  errors:
    missing_required_param: warning # Changed from error to warning
    missing_return: warning # Changed from error to warning
    todo: info
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "lib/generated/**"

linter:
  rules:
    # Essential rules for preventing bugs
    avoid_empty_else: true
    avoid_types_as_parameter_names: true
    avoid_web_libraries_in_flutter: true
    no_duplicate_case_values: true
    valid_regexps: true

    # Basic naming conventions
    camel_case_types: true
    library_names: true

    # Resource management
    cancel_subscriptions: true
    close_sinks: true

    # Flutter specific
    use_build_context_synchronously: true

    # Optional style rules that won't hinder rapid development
    avoid_print: false # Allowed during development
    prefer_single_quotes: false # Made optional
    lines_longer_than_80_chars: false # Made optional
    always_use_package_imports: false # Made optional
    prefer_const_constructors: false # Made optional
    prefer_const_declarations: false # Made optional
    prefer_final_fields: false # Made optional
    prefer_final_locals: false # Made optional
