include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated_plugin_registrant.dart"
  errors:
    invalid_annotation_target: ignore
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    # Style rules
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    always_specify_types: false  # Conflicts with style
    always_use_package_imports: true
    avoid_annotating_with_dynamic: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_positional_boolean_parameters: true
    avoid_redundant_argument_values: true
    avoid_relative_lib_imports: true
    avoid_returning_null_for_future: true
    avoid_returning_this: true
    avoid_setters_without_getters: true
    avoid_type_to_string: true
    avoid_types_on_closure_parameters: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    directives_ordering: true
    flutter_style_todos: true
    leading_newlines_in_multiline_strings: true
    library_private_types_in_public_api: true
    omit_local_variable_types: true
    only_throw_errors: true
    prefer_constructors_over_static_methods: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_interpolation_to_compose_strings: true
    prefer_single_quotes: true
    require_trailing_commas: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_statements: true
    use_if_null_to_convert_nulls_to_bools: true
    use_named_constants: true
    use_raw_strings: true
    use_string_buffers: true

    # Documentation rules
    public_member_api_docs: true

    # Error prevention rules
    avoid_print: true
    cancel_subscriptions: true
    close_sinks: true
    test_types_in_equals: true
    throw_in_finally: true

    # Flutter specific rules
    avoid_unnecessary_containers: true
    use_decorated_box: true
    use_full_hex_values_for_flutter_colors: true

    # Performance rules
    avoid_function_literals_in_foreach_calls: true
    prefer_foreach: true