name: vegavision
description: "AI-powered image editing application"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.1

  # State Management
  provider: ^6.1.4
  get_it: ^8.0.3

  # Firebase/Google Cloud
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  cloud_functions: ^4.6.0

  # Storage & Security
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Image Processing
  camera: ^0.10.5+9 # Official package with raw capture support
  flutter_image_compress: ^2.1.0
  image_gallery_saver: ^2.0.3
  path_provider: ^2.1.2
  path: ^1.8.3

  # Utilities
  uuid: ^4.3.3
  http: ^1.1.2
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  husky: ^0.1.7
  lint_staged: ^0.5.1

  # Testing
  mockito: 5.4.5
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

lint_staged:
  "lib/**.dart":
    - dart format
    - dart analyze
    - dart fix --apply
    - dart test

scripts:
  format: dart format --line-length=100 lib test
  fix: dart fix --apply
  analyze: flutter analyze
  lint: dart run scripts/custom_lint.dart
  check_all: flutter pub run scripts:format && flutter pub run scripts:fix && flutter pub run scripts:analyze && flutter pub run scripts:lint
