name: vegavision
description: "AI-powered image editing application for iOS and Android"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0" # More flexible SDK constraint

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.0
  flutter_spinkit: ^5.0.0
  image_picker: ^1.0.0

  # State Management
  provider: ^6.0.0
  get_it: ^8.0.0

  # Firebase/Google Cloud
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.0
  cloud_firestore: ^4.0.0
  firebase_storage: ^11.0.0
  firebase_messaging: ^14.0.0

  # Storage & Security
  flutter_secure_storage: ^9.0.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0

  # Image Processing
  camera: ^0.10.0
  flutter_image_compress: ^2.0.0
  image_gallery_saver: ^2.0.0
  path_provider: ^2.0.0
  path: ^1.8.0
  vector_math: ^2.1.0
  share_plus: ^7.0.0

  # Mobile-specific utilities
  device_info_plus: ^9.0.0
  connectivity_plus: ^5.0.0
  permission_handler: ^11.0.0

  # Utilities
  uuid: ^4.0.0
  http: ^1.0.0
  logger: ^2.0.0

  # Mobile UI/UX
  modal_bottom_sheet: ^3.0.0
  pull_to_refresh: ^2.0.0
  cloud_functions: ^4.7.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  husky: ^0.1.0
  lint_staged: ^0.4.0

  # Testing
  mockito: ^5.0.0
  build_runner: ^2.0.0
  hive_generator: ^2.0.0

  # Native splash screen generation
  flutter_native_splash: ^2.0.0

  # App icon generation
  flutter_launcher_icons: ^0.13.0

flutter:
  uses-material-design: true

# Configure native splash screen
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash/splash.png
  color_dark: "#121212"
  image_dark: assets/splash/splash_dark.png
  android: true
  ios: true
  web: false

# Configure app icons
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/icon_foreground.png"
  min_sdk_android: 21 # Android 5.0

lint_staged:
  "lib/**.dart":
    - dart format
    - dart analyze
    - dart fix --apply
    - dart test

scripts:
  format: dart format --line-length=100 lib test
  fix: dart fix --apply
  analyze: flutter analyze
  lint: dart run scripts/custom_lint.dart
  check_all: flutter pub run scripts:format && flutter pub run scripts:fix && flutter pub run scripts:analyze && flutter pub run scripts:lint
  build_android: flutter build apk --release
  build_ios: flutter build ios --release --no-codesign
  generate_splash: flutter pub run flutter_native_splash:create
