name: vegavision
description: "AI-powered image editing application for iOS and Android"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0" # More flexible SDK constraint

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.0
  flutter_spinkit: ^5.0.0
  image_picker: ^1.0.0

  # State Management
  provider: ^6.0.0
  get_it: ^8.0.0

  # Firebase/Google Cloud
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.0
  cloud_firestore: ^4.0.0
  firebase_storage: ^11.0.0
  firebase_messaging: ^14.0.0

  # Storage & Security
  flutter_secure_storage: ^9.0.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0

  # Image Processing
  camera: ^0.10.0
  flutter_image_compress: ^2.0.0
  image_gallery_saver: ^2.0.0
  path_provider: ^2.0.0
  path: ^1.8.0
  vector_math: ^2.1.0
  share_plus: ^7.0.0

  # Mobile-specific utilities
  device_info_plus: ^9.0.0
  connectivity_plus: ^5.0.0
  permission_handler: ^11.0.0

  # Utilities
  uuid: ^4.0.0
  http: ^1.0.0
  logger: ^2.0.0

  # Mobile UI/UX
  modal_bottom_sheet: ^3.0.0
  pull_to_refresh: ^2.0.0
  cloud_functions: ^4.7.6

dev_dependencies:
  # Core testing
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  bloc_test: ^9.1.5
  fake_async: ^1.3.1
  golden_toolkit: ^0.15.0
  
  # Code generation
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  hive_generator: ^2.0.1
  
  # Analysis & Linting
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0
  custom_lint: ^0.5.8
  dcm: ^1.0.0  # Replacing dart_code_metrics
  dart_style: ^2.3.4
  effective_dart: ^1.3.2
  
  # Code Quality
  code_coverage: ^1.4.0
  test_cov_console: ^0.2.2
  dependency_validator: ^3.2.3
  import_sorter: ^4.6.0
  dart_code_metrics_presets: ^2.9.0
  
  # Development tools
  husky: ^0.1.0
  lint_staged: ^0.4.0
  mason_cli: ^0.1.0-dev.52
  
  # Documentation
  dartdoc: ^8.3.2  # Updated version to resolve conflict with dart_style
  
  # Native splash & icons
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.13.1

# Flutter configuration
flutter:
  uses-material-design: true

# Configure native splash screen
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash/splash.png
  color_dark: "#121212"
  image_dark: assets/splash/splash_dark.png
  android: true
  ios: true
  web: false

# Configure app icons
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/icon_foreground.png"
  min_sdk_android: 21 # Android 5.0

# Configure DCM (formerly dart_code_metrics)
dcm:
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - no-boolean-literal-compare
    - no-empty-block
    - no-equal-then-else
    - no-object-declaration
    - prefer-conditional-expressions
    - prefer-trailing-comma
    - always-remove-listener
    - avoid-dynamic
    - avoid-implementing-value-types
    - avoid-returning-widgets
    - avoid-unnecessary-setstate
    - avoid-wrapping-in-padding
    - double-literal-format
    - no-boolean-literal-compare
    - prefer-const-border-radius
    - prefer-extracting-callbacks
    - prefer-single-widget-per-file
  anti-patterns:
    - long-method
    - long-parameter-list

# Configure import sorting
import_sorter:
  comments: false
  ignored_files:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated/**"
  emojis: false

# Configure lint_staged
lint_staged:
  "lib/**.dart":
    - dart format
    - dart analyze
    - dart fix --apply
    - flutter test
    - dart run import_sorter:main
    - dart run dcm:metrics analyze lib
    - dart run dependency_validator

# Script commands
scripts:
  format: dart format --line-length=100 lib test
  fix: dart fix --apply
  analyze: flutter analyze
  lint: dart run scripts/custom_lint.dart
  test: flutter test --coverage
  test_coverage: genhtml coverage/lcov.info -o coverage/html
  generate_mocks: flutter pub run build_runner build --delete-conflicting-outputs
  integration_test: flutter test integration_test
  metrics: dart run dcm:metrics analyze lib
  docs: dart doc .
  validate_deps: dart run dependency_validator
  sort_imports: dart run import_sorter:main
  check_all: |
    flutter pub run scripts:format && 
    flutter pub run scripts:fix && 
    flutter pub run scripts:analyze && 
    flutter pub run scripts:lint &&
    flutter pub run scripts:test &&
    flutter pub run scripts:metrics &&
    flutter pub run scripts:validate_deps &&
    flutter pub run scripts:sort_imports
  build_android: flutter build apk --release
  build_ios: flutter build ios --release --no-codesign
  generate_splash: flutter pub run flutter_native_splash:create