// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3e9E35vXGBffDwnzc2ZtTpxR15-CpU-g',
    appId: '1:642331528519:web:7ce0bee53b496aa583d062',
    messagingSenderId: '642331528519',
    projectId: 'vega-vision-da813',
    authDomain: 'vega-vision-da813.firebaseapp.com',
    storageBucket: 'vega-vision-da813.firebasestorage.app',
    measurementId: 'G-WXG1C919J9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPij3n-dgKj6boKWub4QjmDO39ddLvilo',
    appId: '1:642331528519:android:cd3c148655eff06283d062',
    messagingSenderId: '642331528519',
    projectId: 'vega-vision-da813',
    storageBucket: 'vega-vision-da813.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgfhYVYCbB4OTJw12r0fUR7TRvotQ4mIg',
    appId: '1:642331528519:ios:47e5e4ea844f5f3783d062',
    messagingSenderId: '642331528519',
    projectId: 'vega-vision-da813',
    storageBucket: 'vega-vision-da813.firebasestorage.app',
    iosBundleId: 'com.example.vegavision',
  );
}
